### ISSUE TITLE
Feedback zum Testat vom 07.05.2015

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-15#11]
Die Lösung erhält **60 Punkte**.

#### UML generell (-10)
* Es fehlen die Beziehungen zwischen Gesellschaften und Finanzamt (Steuern)
* Es fehlen die Beziehungen zwischen Finanzamt und den Einwohnern von Metropolis
* Es fehlen die Beziehungen zwischen den Einwohnern von Metropolis und den Gesellschaften

#### UML einwohner (-5)
* Die Beziehung zwischen Held und Superkraft sollte keine Komposition sein, eher eine Aggregation. Eine Superkraft kann auch existieren, wenn es keinen Schurken/Helden gibt, er sie gerade hat.

#### Klasse Schurke (-2)
* Redundanz bei der Berechnung: Bei der Berechnung der Gesamtsteuer ist der Aufruf der Berechnungen eXSteuerberechnen zwar gut gedacht, aber redundant. Es wäre möglicherweise besser, die Berechnung ausschließlich in einer Methode unterzubringen.

#### Klasse Finanzamt (-13)
* Das Finanzamt sollte laut Aufgabenstellung "alle Steuerpflichtigen von Metropolis" kennen. Das fehlt vollständig. Eine Liste aller steuerpflichtigen wäre hilfreich. (-3)
* Es ist für die Gesamtberechnung der Steuer nicht möglich, mehr als einen Schurken, oder Syndikat anzugeben. Hier am Besten mit Ellipsen arbeiten. (-2)
* Die Nutzung der Variablen ist nicht klar. Bitte so arbeiten, dass andere lesen können, was gemeint ist. Bsp.: einkommenssteuer = schurke; koerperschaftssteuer = syndikat; (-3)
* Die Steuerberechnung für die Schurken ist fehlerhaft. Ich sehe leider nicht, wie, da die Sortierung des Codes zu lange dauern würde. Die Steuer für onox alleine sollte 82.680 sein (1600 + 6000 + 15.000 + 60.080) (-5)
* PS: Warum macht ihr eine zeitlich aufwändige Ausgabe der Gesamtsteuer über toString, wenn eine einfache Rückgabe des Wertes als int aus der Methode "berechneGesamteSteuern" gereicht hätte?

#### Klasse Syndikat (-5)
* Der Aufruf der Methode "kSteuerBerechnen" erfordert, dass man vorher die Methode "gesamtBerechnen" aufruft. Wenn jemand nach euch das Programm verwenden sollte, der das nicht weiß, entstehen Fehler. Schafft die Voraussetzungen lieber durch Methodenaufrufe in der Klasse selbst oder macht die Berechnung vollständig in einer Methode.

#### Klasse Hauptprogramm (-5)
* Die Berechnung der Steuer entspricht nicht der Aufgabenstellung: Schurken zahlen "doppelt": Einmal als Schurke alleine und dann nochmal über das Syndikat, wenn sie dazu gehören.
Der Aufruf der Berechnung müsste **finanzamt.berechneGesamteSteuern(onox, azok, hannibal, syndikat);** heißen, um das richtige Ergebnis zu liefern.

**Comment by bsra** [comment]
Ich glaube da muss ein Missverständnis sein, denn einige Punkte, die du angesprochen hast, haben wir nach Absprache mit Herrn Smits modelliert.

**Comment by KaroBee** [comment]
Hallo bsra, ich werde Hr. Smits bitten, sich die Bewertung eurer Aufgabe anzuschauen und bei Bedarf zu korrigieren.

**Comment by thomsmits** [comment]
Hallo,

welche der oben genannten Punkte sind mit mir abgesprochen?

Mit freundlichen Grüßen

  Thomas Smits

**Comment by bsra** [comment]
Hallo Herr Smits,

zum einen die Beziehung zwischen Held und Superkraft, welche wir als Komposition dargestellt haben. Dies fragten wir Sie in der Übungsstunde und Sie meinten es sei eine Komposition. 

Und zum anderen die Klasse Finanzamt, denn das hatte ich Sie letzten Mittwoch vor der Vorlesung gefragt und sie meinten es sei eine Aggregation (also Finanzamt zu den einzelnen Steuern). 
Letzten Mittwoch hatte ich Ihnen das Diagramm vorgezeigt, wir hatten als erstes Beziehungen zwischen Finanzamt und jeweilis Buerger, Unternehmen und Schurken. Aber da wir uns unsicher waren hatten wir es dabei und fragten sie nochmal vor der Vorlesung.

Unser Problem war, dass wir mit Signavio gearbeitet haben und da kann man Packages nicht darstellen, deshalb hatten wir jedes Package einzeln als Pdf-Datei hochgeladen. Jedoch haben wir das komplette Diagramm nicht hochgeladen , da wir es eben nicht in Packages einteilen konnten. Aber wir hatten es während dem Testat dabei und die Karoline meinte, dass es auch sehr gut sei. Allerdings mussten wir eben nach der Implementierung einige neue Attribute hinzufügen, deshalb konnte sie das nicht mitnehmen.

Mit freundlichen Grüßen

Büsra Yildiz

**Comment by thomsmits** [comment]
Hallo,

Held->Superkraft: Ein Held ohne Superkraft kann nicht existieren, sonst ist er kein Superheld. Insofern, ist hier eine Komposition OK. Ob jetzt eine Superkraft ohne Helden existieren kann, kann man diskutieren.

Finanzamt: Ein Finanzamt ohne Steuerpflichtige ist zwar ziemlich sinnlos, kann aber existieren. Also ist eine Aggregation OK. Ebenso kann ein Steuerpflichtiger ohne Finanzamt leben.

Finanzamt: Das Diagramm ist auch (weitgehend) in Ordnung, aber die Implementierung ist es nicht. Im Diagramm ist eine Aggregation eingezeichnet, aber im Quelltext findet sich diese nicht.

Das Signavio-Problem ist natürlich ärgerlich, sodass wir die fehlenden Assoziationen hier nicht bewerten wollen. +10. Allerdings sind die Beziehungen manchmal als Attribute (z.B. bei Kapitalgesellschaft) und manchmal nicht angegeben (z.B. bei Syndikat), dafür würde ich direkt wieder -5 Punkte geben.

Die Bewertung von Frau Brunow ist also in Ordnung. Für die diskussionswürdige Frage, bezüglich des Superhelden und der Komposition würde ich +5 Punkte drauflegen.

In Summe sind wir also bei: **70 Punkten**.

Mit freundlichen Grüßen

  Thomas Smits

**Comment by taib06** [comment]
Hallo Herr Smits,

in der Laborstunde haben sie zu mir gesagt, dass man die Attribute weglassen kann, aber nicht muss.
Und bei der Bewertung steht unter Finanzamt ein Abzug von 3 Punkten, weil das Finanzamt die Steuerpflichtigen nicht kennt. Jedoch, nach der Absprache mit ihnen wie oben benannt, haben wir diese doch mit der Aggregation hergestelllt. Ebenfalls haben wir Abzüge wegen der fehlenden Beziehung zwischen den Einwohnern und Gesellschaften bekommen, obwohl diese auch eingezeichnet sind.

Mit freundlichen Grüßen 

Taib Demirci

**Comment by thomsmits** [comment]
Hallo,

die Kritik richtet sich gegen die Implementierung von `Finanzamt`, die falsch ist, weil anstatt einer Liste oder eines Arrays von Steuerpflichtigen, nur eine einfache Referenz deklariert ist. Es geht also nicht um das UML-Diagramm. Der Abzug ist somit gerechtfertigt.

Mit freundlichen Grüßen

  Thomas Smits
